version: '2'
services:
  syslogforwarder:
    restart: always
    build: ./syslogforwarder
    privileged: true
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080